// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Aa: typeof import('./src/components/aa.vue')['default']
    DataTableBlock: typeof import('./src/components/DataTableBlock.vue')['default']
    DialogBlock: typeof import('./src/components/DialogBlock.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Header: typeof import('./src/components/Header.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    'Navbar copy': typeof import('./src/components/Navbar copy.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    PaginationBar: typeof import('./src/components/PaginationBar.vue')['default']
    PaginationBlock: typeof import('./src/components/PaginationBlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    S: typeof import('./src/components/s.vue')['default']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    'SearchBar copy': typeof import('./src/components/SearchBar copy.vue')['default']
    SearchBlock: typeof import('./src/components/SearchBlock.vue')['default']
    'SearchBlock copy': typeof import('./src/components/SearchBlock copy.vue')['default']
    Ss: typeof import('./src/components/ss.vue')['default']
    TableBlock: typeof import('./src/components/TableBlock.vue')['default']
  }
}

export { }
